#' Plot telomeric variants and canonical vs variant proportion
#'
#' This function takes the data frame generated by `detect_TVS()` and produces
#' two useful plots for visualizing telomeric repeats:
#'
#' **1. Bar plot** showing the most frequent variants
#' **2. Pie chart** showing the proportion between canonical and variant repeats
#'
#' @param variant_df A data frame generated by `detect_TVS()`, containing
#'   canonical and variant repeats. The object must include the columns:
#'   `seq_match`, `type`, and `variant`.
#'
#' @return A list containing two `ggplot2` objects:
#' \describe{
#'   \item{bar_plot}{Bar plot with recurrent variants (`n > 1`).}
#'   \item{pie_plot}{Pie chart showing the proportion of canonical vs variant repeats.}
#' }
#'
#' If the data frame is empty, the function returns `NULL` and issues a warning.
#'
#' @examples
#' \dontrun{
#' result <- detect_TVS("example.fasta", repeticao_canon = "TTAGGG")
#' plots <- plot_TVS(result)
#'
#' # Display plots
#' plots$bar_plot
#' plots$pie_plot
#' }
#'
#' @importFrom dplyr filter count mutate
#' @importFrom ggplot2 ggplot aes geom_col coord_flip coord_polar geom_text labs theme_minimal theme element_text
#' @importFrom stats reorder
#' @export
plot_TVS <- function(variant_df) {

  if (is.null(variant_df) || nrow(variant_df) == 0) {
    warning("The data frame is empty. It is not possible to generate plots.")
    return(NULL)
  }

  # -------------------------------
  # BAR PLOT OF VARIANT SEQUENCES
  # -------------------------------
  # Filter only variants (variant == TRUE)
  bar_plot <- variant_df %>%
    dplyr::filter(variant == TRUE) %>%
    dplyr::count(seq_match, sort = TRUE) %>%
    dplyr::filter(n > 1) %>%  # show only recurrent variants
    ggplot2::ggplot(ggplot2::aes(x = stats::reorder(seq_match, n), y = n)) +
    ggplot2::geom_col(fill = "#0072B2") +
    ggplot2::coord_flip() +
    ggplot2::labs(
      title = "Most frequent telomeric variants (> 1 occurrence)",
      x = "Variant",
      y = "Frequency"
    ) +
    ggplot2::theme_minimal() +
    ggplot2::theme(plot.title = ggplot2::element_text(face = "bold"))

  # -------------------------------
  # PIE CHART (CANONICAL vs VARIANT)
  # -------------------------------
  pie_plot <- variant_df %>%
    # The 'type' column already exists in the adapted function output
    dplyr::count(type) %>%
    # Calculate percentages
    dplyr::mutate(percent = n / sum(n) * 100,
                  label = paste0(type, "\n", round(percent, 1), "%")) %>%
    ggplot2::ggplot(ggplot2::aes(x = "", y = n, fill = type)) +
    ggplot2::geom_col(width = 1) +
    ggplot2::coord_polar(theta = "y") +
    # Add percentage labels
    ggplot2::geom_text(ggplot2::aes(y = n / 2 + c(0, cumsum(n)[-length(n)]),
                                    label = label),
                       color = "black", size = 4) +
    ggplot2::labs(
      title = "Proportion between canonical and variant repeats",
      fill = "Repeat Type"
    ) +
    ggplot2::theme_minimal() +
    ggplot2::theme(
      axis.text = ggplot2::element_blank(),
      axis.title = ggplot2::element_blank(),
      panel.grid = ggplot2::element_blank(),
      plot.title = ggplot2::element_text(face = "bold")
    )

  # return both figures
  return(list(
    bar_plot = bar_plot,
    pie_plot = pie_plot
  ))
}
